spring.application.name=currency-service
server.port=8082


spring.cloud.discovery.enabled=true
eureka.client.enabled=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

exchange.api.url=https://api.exchangerate-api.com/v4/latest/
exchange.api.timeout=5000
