spring.application.name=gateway-service

server.port=8090

spring.cloud.discovery.enabled=true
eureka.client.enabled=true

# Gateway routes
spring.cloud.gateway.routes[0].id=r1
spring.cloud.gateway.routes[0].uri=http://localhost:3001
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/payments/**, /api/payments

spring.cloud.gateway.routes[1].id=r2
spring.cloud.gateway.routes[1].uri=http://localhost:8081

spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory/**, /inventory


spring.cloud.gateway.routes[2].id=r3
spring.cloud.gateway.routes[2].uri=http://localhost:8085

spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**, /orders



spring.cloud.gateway.routes[3].id=r4
spring.cloud.gateway.routes[3].uri=http://localhost:8088

spring.cloud.gateway.routes[3].predicates[0]=Path=/shipping/**, /shipping

spring.cloud.gateway.routes[4].id=r5
spring.cloud.gateway.routes[4].uri=http://localhost:8082
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/currency/**, /api/currency

spring.cloud.gateway.routes[5].id=r6
spring.cloud.gateway.routes[5].uri=http://localhost:8092
spring.cloud.gateway.routes[5].predicates[0]=Path=/billing/**, /billing
